# Default Config File for discord-pmmp
# https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

# Sample
# send: true
# webhook: "https://discordapp.com/api/webhooks/123456789123456/fgnaobgaobg"
# username: "Minecraft"
# avatarurl "https://avatars1.githubusercontent.com/u/33122816?s=460&v=4"

onlinemessage:
  send: false
  webhook: ""
  username: "InkoHX"
  avatarurl: "https://avatars1.githubusercontent.com/u/33122816?s=460&v=4"
offlinemessage:
  send: false
  webhook: ""
  username: "InkoHX"
  avatarurl: "https://avatars1.githubusercontent.com/u/33122816?s=460&v=4"
whitelistmessage:
  send: false
  webhook: ""
  username: "InkoHX"
  avatarurl: "https://avatars1.githubusercontent.com/u/33122816?s=460&v=4"
serverchat:
  send: false
  webhook: ""
  username: "InkoHX"
  avatarurl: "https://avatars1.githubusercontent.com/u/33122816?s=460&v=4"

# Embed
embed:
  online:
    title: "SERVER STATUS"
    field: "ONLINE"
    value: "Server opend"
    color: 65280
  offline:
    title: "SERVER STATUS"
    field: "OFFLINE"
    value: "Server closed"
    color: 16711680
  whitelist:
    enable:
      title: "SERVER STATUS"
      field: "WHITELIST"
      value: "Whitelist enable"
      color: 16776960
    disable:
      title: "SERVER STATUS"
      field: "WHITELIST"
      value: "Whitelist disable"
      color: 10026752
